# Generated by Django 4.2.1 on 2023-06-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_habilidad_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidad',
            },
        ),
        migrations.DeleteModel(
            name='Habilidad',
        ),
        migrations.AddField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='habilidades',
            field=models.ManyToManyField(to='personas.habilidades'),
        ),
    ]
